import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Target, Plus, ArrowUpRight, CircleCheck, Clock3, Flame, X, History, TrendingUp } from 'lucide-react';
import { GOAL_TYPES, Goal, GoalHistory, GoalType, GoalMilestone, calculateProgress, getGoalHealth, getProjectedDate, getRequiredDailyPace } from './goalModel';

const STORAGE_KEY = 'thebox.goals.v1';
const initialGoals: Goal[] = [
  { id:'capital-one',name:'Pay Off Capital One',type:'debt',description:'',startDate:'2026-01-01',targetDate:'2027-12-31',target:6000,current:4250,unit:'$',context:'Capital One',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z',history:[] },
  { id:'emergency-fund',name:'Build Emergency Fund',type:'savings',description:'',startDate:'2026-01-01',targetDate:'2026-12-31',target:5000,current:3200,unit:'$',context:'',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z' },
  { id:'python',name:'Learn Python',type:'learning',description:'',startDate:'2026-01-01',targetDate:'2027-03-01',target:100,current:64,unit:'lessons',context:'',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z' },
  { id:'running',name:'Run 100 Miles',type:'fitness',description:'',startDate:'2026-01-01',targetDate:'2026-11-30',target:100,current:42,unit:'miles',context:'',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z' },
];
const today = () => new Date().toISOString().slice(0,10);

export function App() {
  const [goals,setGoals] = useState<Goal[]>(() => { const saved=localStorage.getItem(STORAGE_KEY); return saved ? JSON.parse(saved) : initialGoals; });
  const [showNewGoal,setShowNewGoal] = useState(false);
  useEffect(() => localStorage.setItem(STORAGE_KEY,JSON.stringify(goals)),[goals]);
  const active=goals.filter(g=>g.status==='active'), completed=goals.filter(g=>g.status==='completed');
  const nextGoal=[...active].sort((a,b)=>a.targetDate.localeCompare(b.targetDate))[0];
  const onTrack=active.filter(g=>calculateProgress(g)>=50).length;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Target size={19} strokeWidth={2.5}/></div><div><div className="brand-name">TheBox</div><div className="brand-subtitle">Universal Goals</div></div></div>
      <nav className="nav"><a className="nav-item active" href="#dashboard">Dashboard</a><a className="nav-item" href="#goals">All goals <span>{goals.length}</span></a><a className="nav-item" href="#calendar">Calendar</a><a className="nav-item" href="#wins">Wins</a></nav>
      <div className="sidebar-footer"><div className="box-tip"><span className="tip-label">THE BOX TIP</span><p>Small progress still counts. TheBox is built to help you see it.</p></div><div className="profile"><div className="avatar">N</div><div><strong>My goals</strong><span>Personal workspace</span></div></div></div>
    </aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">YOUR PROGRESS</p><h1>Make progress. <em>Keep going.</em></h1></div><button className="primary-button" onClick={()=>setShowNewGoal(true)}><Plus size={18}/> New goal</button></header>
      <section className="stats"><Stat icon={<Target/>} label="Active goals" value={String(active.length)}/><Stat icon={<Flame/>} label="On track" value={String(onTrack)}/><Stat icon={<CircleCheck/>} label="Completed" value={String(completed.length)}/><Stat icon={<Clock3/>} label="Next deadline" value={nextGoal ? daysLeft(nextGoal.targetDate)+'d':'—'} detail={nextGoal?.name}/></section>
      <section className="content-grid"><div className="goals-panel"><div className="section-heading"><div><h2>Your goals</h2><p>Everything you're working toward.</p></div><a href="#goals">View all <ArrowUpRight size={15}/></a></div><div className="goal-list">{goals.map(g=><GoalCard key={g.id} goal={g} onUpdate={()=>setSelected(g)}/>)}</div></div>
        <aside className="momentum"><div className="section-heading"><div><h2>Momentum</h2><p>Your recent movement.</p></div></div><div className="momentum-number">{Math.round(goals.reduce((s,g)=>s+calculateProgress(g),0)/Math.max(goals.length,1))}<span>%</span></div><p className="momentum-copy">average goal progress</p><div className="activity"><div className="activity-dot"/><div><strong>{goals.length} goals in TheBox</strong><span>Keep building your streak.</span></div></div><div className="activity"><div className="activity-dot"/><div><strong>{completed.length} completed</strong><span>Every finished goal becomes a win.</span></div></div></aside>
      </section>
    </main>
    {showNewGoal && <NewGoalModal onClose={()=>setShowNewGoal(false)} onCreate={goal=>{setGoals(current=>[goal,...current]);setShowNewGoal(false);}}/>}
  </div>;
}
function GoalCard({goal,onUpdate}:{goal:Goal;onUpdate:()=>void}){const progress=Math.round(calculateProgress(goal));const type=GOAL_TYPES.find(t=>t.id===goal.type);const health=getGoalHealth(goal);const projected=getProjectedDate(goal);const pace=getRequiredDailyPace(goal);return <article className="goal-card"><div className="goal-top"><div><div className="goal-type">{type?.icon} {type?.label}</div><h3>{goal.name}</h3>{goal.context&&<p className="goal-context">{goal.context}</p>}</div><span className={`status status-${health}`}>{healthLabel(health)}</span></div><div className="progress-row"><strong>{progress}%</strong><span>{formatValue(goal.current,goal.unit)} / {formatValue(goal.target,goal.unit)}</span></div><div className="progress-track"><div style={{width:progress+'%'}}/></div><div className="milestone-strip">{goal.milestones.map(m=><span key={m.id} className={m.reachedAt?'reached':''} title={m.reachedAt?`Reached ${new Date(m.reachedAt).toLocaleDateString()}`:`${m.percent}% milestone`}>{m.reachedAt?'✓':m.percent+'%'}</span>)}</div><div className="goal-insight">{health!=='complete'&&<><span>Need {formatValue(pace??0,goal.unit)} / day</span>{projected&&<span>Projected {formatDate(projected)}</span>}</>}{health==='complete'&&<span>Goal complete</span>}</div><div className="goal-footer"><span>{daysLeft(goal.targetDate)} days remaining</span><button className="text-button" onClick={onUpdate}><TrendingUp size={13}/> Update progress</button></div></article>;}
function NewGoalModal({onClose,onCreate}:{onClose:()=>void;onCreate:(goal:Goal)=>void}){
  const [name,setName]=useState(''),[type,setType]=useState<GoalType>('personal'),[target,setTarget]=useState(''),[current,setCurrent]=useState('0'),[unit,setUnit]=useState('units'),[targetDate,setTargetDate]=useState(''),[context,setContext]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState('');
  const selected=useMemo(()=>GOAL_TYPES.find(t=>t.id===type)!,[type]);
  const submit=(event:FormEvent)=>{event.preventDefault();const t=Number(target),c=Number(current);if(!name.trim()||!targetDate||!Number.isFinite(t)||t<=0||!Number.isFinite(c)||c<0){setError('Add a name, target date, and valid progress values to create the goal.');return;}if(c>t){setError('Current progress cannot be greater than the target.');return;}onCreate({id:crypto.randomUUID(),name:name.trim(),type,description:description.trim(),startDate:today(),targetDate,target:t,current:c,unit:unit.trim()||selected.unitPlaceholder,context:context.trim(),notes:'',status:'active',createdAt:new Date().toISOString(),history:[],milestones:[]});};
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW GOAL</p><h2>Put something in TheBox.</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid">
    <label>Goal name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Save $5,000"/></label><label>Goal type<select value={type} onChange={e=>{const n=e.target.value as GoalType;setType(n);setUnit(GOAL_TYPES.find(t=>t.id===n)!.unitPlaceholder);}}>{GOAL_TYPES.map(t=><option key={t.id} value={t.id}>{t.icon} {t.label}</option>)}</select></label>
    <label>Target<input type="number" min="0" step="any" value={target} onChange={e=>setTarget(e.target.value)} placeholder="5000"/></label><label>Current progress<input type="number" min="0" step="any" value={current} onChange={e=>setCurrent(e.target.value)}/></label>
    <label>Unit<input value={unit} onChange={e=>setUnit(e.target.value)} placeholder={selected.unitPlaceholder}/></label><label>Target date<input type="date" min={today()} value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label>
    <label className="full">Organization / context<input value={context} onChange={e=>setContext(e.target.value)} placeholder="e.g. Capital One, Python course, marathon"/></label><label className="full">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What does success look like?" rows={3}/></label>
  </div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit"><Plus size={17}/> Create goal</button></div></form></div>;
}
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail?:string}){return <div className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div></div>;}
function healthLabel(h:ReturnType<typeof getGoalHealth>){return h==='complete'?'Complete':h==='on-track'?'On track':h==='at-risk'?'At risk':'Behind';}
function formatDate(date:string){return new Date(date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function daysLeft(date:string){return Math.max(0,Math.ceil((new Date(date).getTime()-Date.now())/86400000));}
function formatValue(value:number,unit:string){return unit==='$'?'$'+value.toLocaleString():value.toLocaleString()+' '+unit;}

function ProgressModal({goal,onClose,onUpdate}:{goal:Goal;onClose:()=>void;onUpdate:(value:number,note:string)=>void}){const[amount,setAmount]=useState(String(goal.current)),[note,setNote]=useState('');const next=Number(amount);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><p className="eyebrow">UPDATE PROGRESS</p><h2>{goal.name}</h2></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="update-summary"><div><span>Current</span><strong>{formatValue(goal.current,goal.unit)}</strong></div><div className="change-arrow">→</div><div><span>New total</span><strong>{formatValue(Number.isFinite(next)?next:goal.current,goal.unit)}</strong></div></div><label className="modal-label">New progress<input type="number" min="0" max={goal.target} step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="modal-label">Note <span>optional</span><input value={note} onChange={e=>setNote(e.target.value)} placeholder={goal.type==='debt'?'e.g. Payment made':'e.g. Finished another chapter'}/></label>{goal.history.length>0&&<div className="history"><div className="history-title"><History size={14}/> Recent updates</div>{goal.history.slice(0,3).map(h=><div className="history-row" key={h.id}><span>{new Date(h.createdAt).toLocaleDateString()}</span><strong>{h.change>=0?'+':''}{formatValue(h.change,goal.unit)}</strong><small>{h.note||'Progress update'}</small></div>)}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!Number.isFinite(next)||next<0||next>goal.target} onClick={()=>onUpdate(next,note.trim())}>Save progress</button></div></div></div>;}
