import { useEffect, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Target, Plus, ArrowUpRight, CircleCheck, Clock3, Flame, X, History, TrendingUp, MapPin, Check, DollarSign } from 'lucide-react';
import { GOAL_TYPES, calculateProgress, getGoalHealth, getProjectedDate, getRequiredDailyPace, getMilestoneDate } from './goalModel';
import type { Goal, GoalType, RelocationTask } from './goalModel';

const STORAGE_KEY = 'thebox.goals.v1';
const makeMilestones=(startDate:string,targetDate:string,current:number,target:number)=>[25,50,75,100].map(percent=>({id:crypto.randomUUID(),title:percent+'% milestone',percent,targetDate:getMilestoneDate({startDate,targetDate},percent),reachedAt:calculateProgress({current,target})>=percent?'2026-01-01T00:00:00.000Z':undefined}));
const initialGoals: Goal[] = [
  { id:'capital-one',name:'Pay Off Capital One',type:'debt',description:'',startDate:'2026-01-01',targetDate:'2027-12-31',target:6000,current:4250,unit:'$',context:'Capital One',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z',history:[],milestones:makeMilestones('2026-01-01','2027-12-31',4250,6000),debt:{originalBalance:6000,interestRate:24.99,minimumPayment:150,monthlyPayment:250} },
  { id:'emergency-fund',name:'Build Emergency Fund',type:'savings',description:'',startDate:'2026-01-01',targetDate:'2026-12-31',target:5000,current:3200,unit:'$',context:'',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z',history:[],milestones:makeMilestones('2026-01-01','2026-12-31',3200,5000) },
  { id:'python',name:'Learn Python',type:'learning',description:'',startDate:'2026-01-01',targetDate:'2027-03-01',target:100,current:64,unit:'lessons',context:'',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z',history:[],milestones:makeMilestones('2026-01-01','2027-03-01',64,100) },
  { id:'running',name:'Run 100 Miles',type:'fitness',description:'',startDate:'2026-01-01',targetDate:'2026-11-30',target:100,current:42,unit:'miles',context:'',notes:'',status:'active',createdAt:'2026-01-01T00:00:00Z',history:[],milestones:makeMilestones('2026-01-01','2026-11-30',42,100) },
];
const today = () => new Date().toISOString().slice(0,10);

export function App() {
  const [goals,setGoalsState]=useState<Goal[]>(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);const raw=saved?JSON.parse(saved):initialGoals;return raw.map((g:Goal)=>({...g,history:g.history??[],milestones:g.milestones??makeMilestones(g.startDate,g.targetDate,g.current,g.target)}));}catch{return initialGoals;}});
  const setGoals=(next:Goal[]|((g:Goal[])=>Goal[]))=>setGoalsState(next);
  const [showNewGoal,setShowNewGoal]=useState(false),[showCalendar,setShowCalendar]=useState(false),[selected,setSelected]=useState<Goal|null>(null),[detail,setDetail]=useState<Goal|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|'active'|'completed'>('all');
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(goals)),[goals]);
  const updateProgress=(goal:Goal,value:number,note:string)=>{setGoals(current=>current.map(g=>{if(g.id!==goal.id)return g;const complete=value>=g.target;return {...g,current:value,status:complete?'completed':'active',completedAt:complete?(g.completedAt||new Date().toISOString()):undefined,history:[{id:crypto.randomUUID(),goalId:g.id,previous:g.current,current:value,change:value-g.current,note,createdAt:new Date().toISOString()},...g.history],milestones:g.milestones.map(m=>({...m,reachedAt:m.reachedAt||(value/g.target*100>=m.percent?new Date().toISOString():undefined)}))};}));setSelected(null);setDetail(null);};
  const filtered=goals.filter(g=>(filter==='all'||(filter==='active'?g.status!=='completed':g.status==='completed'))&&(g.name+' '+g.context+' '+g.type).toLowerCase().includes(query.toLowerCase()));
  const exportData=()=>{const blob=new Blob([JSON.stringify(goals,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='thebox-goals.json';link.click();URL.revokeObjectURL(url);};
  const active=goals.filter(g=>g.status==='active'), completed=goals.filter(g=>g.status==='completed');
  const nextGoal=[...active].sort((a,b)=>a.targetDate.localeCompare(b.targetDate))[0];
  const onTrack=active.filter(g=>calculateProgress(g)>=50).length;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Target size={19} strokeWidth={2.5}/></div><div><div className="brand-name">TheBox</div><div className="brand-subtitle">Universal Goals</div></div></div>
      <nav className="nav"><a className="nav-item active" href="#dashboard">Dashboard</a><a className="nav-item" href="#goals">All goals <span>{goals.length}</span></a><button className="nav-item nav-button" onClick={()=>setShowCalendar(true)}>Calendar</button><a className="nav-item" href="#wins">Wins</a></nav>
      <div className="sidebar-footer"><div className="box-tip"><span className="tip-label">THE BOX TIP</span><p>Small progress still counts. TheBox is built to help you see it.</p></div><div className="profile"><div className="avatar">N</div><div><strong>My goals</strong><span>Personal workspace</span></div></div></div>
    </aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">YOUR PROGRESS</p><h1>Make progress. <em>Keep going.</em></h1></div><button className="primary-button" onClick={()=>setShowNewGoal(true)}><Plus size={18}/> New goal</button></header>
      <section className="stats"><Stat icon={<Target/>} label="Active goals" value={String(active.length)}/><Stat icon={<Flame/>} label="On track" value={String(onTrack)}/><Stat icon={<CircleCheck/>} label="Completed" value={String(completed.length)}/><Stat icon={<Clock3/>} label="Next deadline" value={nextGoal ? daysLeft(nextGoal.targetDate)+'d':'—'} detail={nextGoal?.name}/></section>
      <section className="content-grid"><div className="goals-panel"><div className="section-heading"><div><h2>Your goals</h2><p>Everything you're working toward.</p></div><button className="text-button" onClick={exportData}>Export data <ArrowUpRight size={15}/></button></div><div className="goal-controls"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search goals..."/><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">All</option><option value="active">Active</option><option value="completed">Completed</option></select></div><div className="goal-list">{filtered.map(g=><GoalCard key={g.id} goal={g} onSelect={setDetail} onUpdate={()=>setSelected(g)}/>)}</div></div>
        <aside className="momentum"><div className="section-heading"><div><h2>Momentum</h2><p>Your recent movement.</p></div></div><div className="momentum-number">{Math.round(goals.reduce((s,g)=>s+calculateProgress(g),0)/Math.max(goals.length,1))}<span>%</span></div><p className="momentum-copy">average goal progress</p><div className="activity"><div className="activity-dot"/><div><strong>{goals.length} goals in TheBox</strong><span>Keep building your streak.</span></div></div><div className="activity"><div className="activity-dot"/><div><strong>{completed.length} completed</strong><span>Every finished goal becomes a win.</span></div></div></aside>
      </section>
    </main>
    {selected && <ProgressModal goal={selected} onClose={()=>setSelected(null)} onUpdate={(v,n)=>updateProgress(selected,v,n)}/>} {detail && <GoalDetail goal={detail} onClose={()=>setDetail(null)} onUpdate={()=>{setSelected(detail);setDetail(null)}} onDelete={()=>{setGoals(current=>current.filter(g=>g.id!==detail.id));setDetail(null)}}/>} {showCalendar&&<CalendarModal goals={goals} onClose={()=>setShowCalendar(false)} onSelect={g=>{setShowCalendar(false);setDetail(g)}}/>} {showNewGoal && <NewGoalModal onClose={()=>setShowNewGoal(false)} onCreate={goal=>{setGoals(current=>[goal,...current]);setShowNewGoal(false);}}/>}
  </div>;
}
function GoalCard({goal,onUpdate,onSelect}:{goal:Goal;onUpdate:()=>void;onSelect:(goal:Goal)=>void}){const progress=Math.round(calculateProgress(goal));const type=GOAL_TYPES.find(t=>t.id===goal.type);const health=getGoalHealth(goal);const projected=getProjectedDate(goal);const pace=getRequiredDailyPace(goal);return <article className="goal-card" onClick={()=>onSelect(goal)}><div className="goal-top"><div><div className="goal-type">{type?.icon} {type?.label}</div><h3>{goal.name}</h3>{goal.context&&<p className="goal-context">{goal.context}</p>}</div><span className={`status status-${health}`}>{healthLabel(health)}</span></div><div className="progress-row"><strong>{progress}%</strong><span>{formatValue(goal.current,goal.unit)} / {formatValue(goal.target,goal.unit)}</span></div><div className="progress-track"><div style={{width:progress+'%'}}/></div><div className="milestone-strip">{goal.milestones.map(m=><span key={m.id} className={m.reachedAt?'reached':''} title={m.reachedAt?`Reached ${new Date(m.reachedAt).toLocaleDateString()}`:`${m.percent}% milestone`}>{m.reachedAt?'✓':m.percent+'%'}</span>)}</div><div className="goal-insight">{health!=='complete'&&<><span>Need {formatValue(pace??0,goal.unit)} / day</span>{projected&&<span>Projected {formatDate(projected)}</span>}</>}{health==='complete'&&<span>Goal complete</span>}</div><div className="goal-footer"><span>{daysLeft(goal.targetDate)} days remaining</span><button className="text-button" onClick={e=>{e.stopPropagation();onUpdate()}}><TrendingUp size={13}/> Update progress</button></div></article>;}
function NewGoalModal({onClose,onCreate}:{onClose:()=>void;onCreate:(goal:Goal)=>void}){
  const [name,setName]=useState(''),[type,setType]=useState<GoalType>('personal'),[target,setTarget]=useState(''),[current,setCurrent]=useState('0'),[unit,setUnit]=useState('units'),[targetDate,setTargetDate]=useState(''),[context,setContext]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState(''),[originalBalance,setOriginalBalance]=useState(''),[apr,setApr]=useState(''),[minimumPayment,setMinimumPayment]=useState(''),[monthlyPayment,setMonthlyPayment]=useState(''),[dueDay,setDueDay]=useState('');
  const selected=useMemo(()=>GOAL_TYPES.find(t=>t.id===type)!,[type]);
  const submit=(event:FormEvent)=>{event.preventDefault();const t=Number(target),cur=Number(current);if(!name.trim()||!targetDate||!Number.isFinite(t)||t<=0||!Number.isFinite(cur)||cur<0||cur>t){setError('Add a name, target date, and valid progress values.');return;}if(type==='debt'&&(!Number(originalBalance)||Number(originalBalance)<=0||!Number.isFinite(Number(apr))||Number(apr)<0||!Number(minimumPayment)||Number(minimumPayment)<=0||!Number(monthlyPayment)||Number(monthlyPayment)<=0)){setError('Debt goals need an original balance, APR, minimum payment, and monthly payment.');return;}const startDate=today();const goal:Goal={id:crypto.randomUUID(),name:name.trim(),type,description:description.trim(),startDate,targetDate,target:t,current:cur,unit:unit.trim()||selected.unitPlaceholder,context:context.trim(),notes:'',status:cur>=t?'completed':'active',completedAt:cur>=t?new Date().toISOString():undefined,createdAt:new Date().toISOString(),history:[],milestones:[25,50,75,100].map(percent=>({id:crypto.randomUUID(),title:percent+'% milestone',percent,targetDate:getMilestoneDate({startDate,targetDate},percent),reachedAt:calculateProgress({current:cur,target:t})>=percent?new Date().toISOString():undefined}))};if(type==='debt')goal.debt={originalBalance:Number(originalBalance),interestRate:Number(apr),minimumPayment:Number(minimumPayment),monthlyPayment:Number(monthlyPayment),dueDay:dueDay?Number(dueDay):undefined};onCreate(goal);};
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW GOAL</p><h2>Put something in TheBox.</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label>Goal name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Save $5,000"/></label><label>Goal type<select value={type} onChange={e=>{const n=e.target.value as GoalType;setType(n);setUnit(GOAL_TYPES.find(t=>t.id===n)!.unitPlaceholder);}}>{GOAL_TYPES.map(t=><option key={t.id} value={t.id}>{t.icon} {t.label}</option>)}</select></label><label>{type==='debt'?'Original balance':'Target'}<input type="number" min="0" step="any" value={target} onChange={e=>{setTarget(e.target.value);if(type==='debt')setOriginalBalance(e.target.value)}} placeholder="5000"/></label><label>{type==='debt'?'Amount paid so far':'Current progress'}<input type="number" min="0" step="any" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>Unit<input value={unit} onChange={e=>setUnit(e.target.value)} placeholder={selected.unitPlaceholder}/></label><label>Target date<input type="date" min={today()} value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label>{type==='debt'&&<div className="debt-form"><div className="debt-form-title">Debt details</div><label>APR %<input type="number" min="0" step="0.01" value={apr} onChange={e=>setApr(e.target.value)} placeholder="24.99"/></label><label>Minimum payment<input type="number" min="0" step="any" value={minimumPayment} onChange={e=>setMinimumPayment(e.target.value)} placeholder="150"/></label><label>Monthly payment<input type="number" min="0" step="any" value={monthlyPayment} onChange={e=>setMonthlyPayment(e.target.value)} placeholder="250"/></label><label>Due day<input type="number" min="1" max="31" value={dueDay} onChange={e=>setDueDay(e.target.value)} placeholder="15"/></label></div>}<label className="full">Organization / context<input value={context} onChange={e=>setContext(e.target.value)} placeholder="e.g. Capital One, Python course, marathon"/></label><label className="full">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What does success look like?" rows={3}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit"><Plus size={17}/> Create goal</button></div></form></div>;
}
function Stat({icon,label,value,detail}:{icon:ReactNode;label:string;value:string;detail?:string}){return <div className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div></div>;}
function healthLabel(h:ReturnType<typeof getGoalHealth>){return h==='complete'?'Complete':h==='on-track'?'On track':h==='at-risk'?'At risk':'Behind';}
function formatDate(date:string){return new Date(date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function daysLeft(date:string){return Math.max(0,Math.ceil((new Date(date).getTime()-Date.now())/86400000));}
function formatValue(value:number,unit:string){return unit==='$'?'$'+value.toLocaleString():value.toLocaleString()+' '+unit;}

function ProgressModal({goal,onClose,onUpdate}:{goal:Goal;onClose:()=>void;onUpdate:(value:number,note:string)=>void}){const[amount,setAmount]=useState(String(goal.current)),[note,setNote]=useState('');const next=Number(amount);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><p className="eyebrow">UPDATE PROGRESS</p><h2>{goal.name}</h2></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="update-summary"><div><span>Current</span><strong>{formatValue(goal.current,goal.unit)}</strong></div><div className="change-arrow">→</div><div><span>New total</span><strong>{formatValue(Number.isFinite(next)?next:goal.current,goal.unit)}</strong></div></div><label className="modal-label">New progress<input type="number" min="0" max={goal.target} step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="modal-label">Note <span>optional</span><input value={note} onChange={e=>setNote(e.target.value)} placeholder={goal.type==='debt'?'e.g. Payment made':'e.g. Finished another chapter'}/></label>{goal.history.length>0&&<div className="history"><div className="history-title"><History size={14}/> Recent updates</div>{goal.history.slice(0,3).map(h=><div className="history-row" key={h.id}><span>{new Date(h.createdAt).toLocaleDateString()}</span><strong>{h.change>=0?'+':''}{formatValue(h.change,goal.unit)}</strong><small>{h.note||'Progress update'}</small></div>)}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!Number.isFinite(next)||next<0||next>goal.target} onClick={()=>onUpdate(next,note.trim())}>Save progress</button></div></div></div>;}
function CalendarModal({goals,onClose,onSelect}:{goals:Goal[];onClose:()=>void;onSelect:(g:Goal)=>void}){const now=new Date();const[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));const year=month.getFullYear(),mo=month.getMonth();const first=new Date(year,mo,1).getDay();const days=new Date(year,mo+1,0).getDate();const cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1);const events=goals.flatMap(g=>[{date:g.targetDate,kind:'deadline',goal:g,label:g.name},...g.milestones.map(m=>({date:m.targetDate||getMilestoneDate(g,m.percent),kind:'milestone',goal:g,label:`${m.percent}% milestone`,offset:m.percent}))]);return <div className="modal-backdrop"><div className="modal calendar-modal"><div className="modal-head"><div><p className="eyebrow">PLANNING</p><h2>Goal Calendar</h2><p className="calendar-sub">Deadlines and milestones in one view.</p></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="calendar-nav"><button className="secondary-button" onClick={()=>setMonth(new Date(year,mo-1,1))}>←</button><strong>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button className="secondary-button" onClick={()=>setMonth(new Date(year,mo+1,1))}>→</button></div><div className="calendar-grid calendar-week">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map((day,i)=>{if(!day)return <div className="calendar-day empty" key={i}/>;const ds=year+'-'+String(mo+1).padStart(2,'0')+'-'+String(day).padStart(2,'0');const dayEvents=events.filter(e=>e.date===ds);return <div className={`calendar-day ${day===now.getDate()&&mo===now.getMonth()&&year===now.getFullYear()?'today':''}`} key={i}><b>{day}</b>{dayEvents.map((e,j)=><button key={j} className={e.kind==='deadline'?'calendar-event deadline':'calendar-event'} onClick={()=>onSelect(e.goal)}>{e.kind==='deadline'?'◆':'•'} {e.label}</button>)}</div>})}</div><div className="calendar-legend"><span><i className="legend-dot deadline-dot"/>Deadline</span><span><i className="legend-dot"/>Milestone</span></div></div></div>;}
function GoalDetail({goal,onClose,onUpdate,onDelete}:{goal:Goal;onClose:()=>void;onUpdate:()=>void;onDelete:()=>void}){const progress=Math.round(calculateProgress(goal));const health=getGoalHealth(goal);const projected=getProjectedDate(goal);const pace=getRequiredDailyPace(goal);const type=GOAL_TYPES.find(t=>t.id===goal.type);return <div className="modal-backdrop"><div className="modal detail-modal"><div className="modal-head"><div><p className="eyebrow">{type?.icon} {type?.label.toUpperCase()}</p><h2>{goal.name}</h2>{goal.context&&<p className="detail-context">{goal.context}</p>}</div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="detail-progress"><div className="detail-progress-top"><strong>{progress}%</strong><span className={`status status-${health}`}>{healthLabel(health)}</span></div><div className="progress-track"><div style={{width:progress+'%'}}/></div></div><div className="detail-metrics"><div><span>Current</span><strong>{formatValue(goal.current,goal.unit)}</strong></div><div><span>Target</span><strong>{formatValue(goal.target,goal.unit)}</strong></div><div><span>Remaining</span><strong>{formatValue(Math.max(0,goal.target-goal.current),goal.unit)}</strong></div><div><span>Deadline</span><strong>{formatDate(goal.targetDate)}</strong></div></div>{goal.type==='debt'&&goal.debt&&<DebtPanel goal={goal}/>}<div className="detail-two-col"><section><h3>Milestones</h3><div className="detail-milestones">{goal.milestones.map(m=><div className={m.reachedAt?'detail-milestone reached':'detail-milestone'} key={m.id}><span>{m.reachedAt?'✓':m.percent+'%'}</span><div><strong>{m.percent}% checkpoint</strong><small>{m.reachedAt?'Reached '+formatDate(m.reachedAt.slice(0,10)):'Not reached yet'}</small></div></div>)}</div></section><section><h3>Projection</h3><div className="projection-box"><div><span>Required pace</span><strong>{pace?formatValue(pace,goal.unit)+' / day':'—'}</strong></div><div><span>Projected finish</span><strong>{projected?formatDate(projected):goal.status==='completed'?'Complete':'Not enough history yet'}</strong></div></div></section></div>{goal.description&&<section className="detail-notes"><h3>About this goal</h3><p>{goal.description}</p></section>}<section className="detail-notes"><h3>Recent history</h3>{goal.history.length?<div className="detail-history">{goal.history.slice(0,8).map(h=><div key={h.id}><span>{formatDate(h.createdAt.slice(0,10))}</span><strong>{h.change>=0?'+':''}{formatValue(h.change,goal.unit)}</strong><small>{h.note||'Progress update'}</small></div>)}</div>:<p>No progress updates yet. Your first update will appear here.</p>}</section><div className="modal-actions"><button className="secondary-button" onClick={onDelete}>Delete goal</button><button className="secondary-button" onClick={onClose}>Close</button><button className="primary-button" onClick={onUpdate}><TrendingUp size={16}/> Update progress</button></div></div></div>;}
function DebtPanel({goal}:{goal:Goal}){const d=goal.debt!;const months=getDebtMonths(goal.current,d.originalBalance,d.interestRate,d.monthlyPayment);return <section className="debt-panel"><div className="debt-heading"><div><p className="eyebrow">DEBT PAYOFF</p><h3>{goal.context||goal.name}</h3></div><span>{d.interestRate.toFixed(2)}% APR</span></div><div className="debt-grid"><div><span>Current balance</span><strong>{formatValue(Math.max(0,d.originalBalance-goal.current),'$')}</strong></div><div><span>Monthly payment</span><strong>{formatValue(d.monthlyPayment,'$')}</strong></div><div><span>Minimum payment</span><strong>{formatValue(d.minimumPayment,'$')}</strong></div><div><span>Est. payoff</span><strong>{months===null?'—':months+' mo.'}</strong></div></div>{d.monthlyPayment<d.minimumPayment&&<p className="debt-warning">Monthly payment is below the recorded minimum payment.</p>}</section>;}
function getDebtMonths(balancePaid:number,originalBalance:number,apr:number,payment:number){const balance=Math.max(0,originalBalance-balancePaid);if(balance<=0)return 0;if(payment<=0)return null;const r=apr/100/12;if(r>0&&payment<=balance*r)return null;return Math.ceil(r===0?balance/payment:-Math.log(1-balance*r/payment)/Math.log(1+r));}
